"""add_btree_index_to_gc_content

Revision ID: a6bd93b9924e
Revises: 742352330c77
Create Date: 2026-03-24 21:03:29.273504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6bd93b9924e'
down_revision: Union[str, Sequence[str], None] = '742352330c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_genes_gc_content'), 'genes', ['gc_content'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genes_gc_content'), table_name='genes')
    # ### end Alembic commands ###
