"""add gc_content and description to genes

Revision ID: ff397fc6fca2
Revises: 96c15cbdee34
Create Date: 2026-03-21 10:33:38.088650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff397fc6fca2'
down_revision: Union[str, Sequence[str], None] = '96c15cbdee34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genes', sa.Column('gc_content', sa.Float(), nullable=True))
    op.add_column('genes', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genes', 'description')
    op.drop_column('genes', 'gc_content')
    # ### end Alembic commands ###
